In [2]:
import numpy as np

Array Operations

Arithmetic Operations

In [4]:
a1 = np.array([1, 2, 3, 4, 5])
a2 = np.array([6, 7, 8, 9, 10])

In [5]:
a1 + a2 #Size must be same of both the arrays

array([ 7,  9, 11, 13, 15])

In [6]:
a1 - a2

array([-5, -5, -5, -5, -5])

In [7]:
a1 * a2

array([ 6, 14, 24, 36, 50])

In [8]:
a1 / a2

array([0.16666667, 0.28571429, 0.375     , 0.44444444, 0.5       ])

In [9]:
a1 // a2

array([0, 0, 0, 0, 0])

In [10]:
a1 ** a2

array([      1,     128,    6561,  262144, 9765625])

Broadcasting

In [11]:
l = [10, 20, 30, 40]
arr = np.array(l)

In [12]:
arr + 10

array([20, 30, 40, 50])

In [13]:
arr2 = np.arange(1, 26).reshape(5, 5)

In [14]:
arr2 + 10

array([[11, 12, 13, 14, 15],
       [16, 17, 18, 19, 20],
       [21, 22, 23, 24, 25],
       [26, 27, 28, 29, 30],
       [31, 32, 33, 34, 35]])

In [15]:
arr2 * 2

array([[ 2,  4,  6,  8, 10],
       [12, 14, 16, 18, 20],
       [22, 24, 26, 28, 30],
       [32, 34, 36, 38, 40],
       [42, 44, 46, 48, 50]])

Deep and Shallow copy

In [16]:
a = np.arange(1, 21)
a

array([ 1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14, 15, 16, 17,
       18, 19, 20])

In [17]:
slice = a[:5]
slice = slice * 10
slice

array([10, 20, 30, 40, 50])

In [18]:
a
b = a #This is Shallow copy, pointing to the same location
# For deep copy use b = a.copy() 

In [19]:
b[0] = 99

In [20]:
b

array([99,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14, 15, 16, 17,
       18, 19, 20])

In [21]:
a

array([99,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14, 15, 16, 17,
       18, 19, 20])

Matrix Operations

In [22]:
A = np.array([[1, 2], [3, 4]])
B = np.array([[5, 6], [7, 8]])

In [23]:
A

array([[1, 2],
       [3, 4]])

In [24]:
B

array([[5, 6],
       [7, 8]])

In [25]:
A * B # Index Matrix Multiplication

array([[ 5, 12],
       [21, 32]])

In [26]:
A @ B # Actual Matrix multiplication

array([[19, 22],
       [43, 50]])

In [27]:
np.dot(A, B)

array([[19, 22],
       [43, 50]])

In [28]:
np.transpose(A) # Rows become columns and vice-versa

array([[1, 3],
       [2, 4]])

In [29]:
np.transpose(B)

array([[5, 7],
       [6, 8]])

Advance Array Manipulation

Stacking Array

In [30]:
A

array([[1, 2],
       [3, 4]])

In [31]:
B

array([[5, 6],
       [7, 8]])

You cannot stack 2 matrices cause they are already
stacked, you can only stack vectors

In [32]:
a = np.array([1, 2, 3, 4])
b = np.array([5, 6, 7, 8])

In [33]:
np.vstack((a, b)) # Vertical Stack, row-wise

array([[1, 2, 3, 4],
       [5, 6, 7, 8]])

In [34]:
np.hstack((a, b)) # Horizonatl Stack, col-wise

array([1, 2, 3, 4, 5, 6, 7, 8])

In [35]:
np.column_stack((a, b)) # Column Stack

array([[1, 5],
       [2, 6],
       [3, 7],
       [4, 8]])

Splitting Array

In [36]:
c = np.arange(16).reshape(4, 4)
c

array([[ 0,  1,  2,  3],
       [ 4,  5,  6,  7],
       [ 8,  9, 10, 11],
       [12, 13, 14, 15]])

In [46]:
np.hsplit(c, 2) # Has to be equal division

[array([[ 0,  1],
        [ 4,  5],
        [ 8,  9],
        [12, 13]]),
 array([[ 2,  3],
        [ 6,  7],
        [10, 11],
        [14, 15]])]

In [45]:
np.vsplit(c, 2) # Has to be equal division

[array([[0, 1, 2, 3],
        [4, 5, 6, 7]]),
 array([[ 8,  9, 10, 11],
        [12, 13, 14, 15]])]