In [1]:
import numpy as np

Numpy indexing and slicing of vectors

In [3]:
arr = np.arange(11, 21)
arr

array([11, 12, 13, 14, 15, 16, 17, 18, 19, 20])

In [11]:
arr[6] #Indexing

np.int64(17)

In [12]:
arr[1:5] #Slicing

array([12, 13, 14, 15])

In [6]:
arr[:5]

array([11, 12, 13, 14, 15])

In [7]:
arr[:]

array([11, 12, 13, 14, 15, 16, 17, 18, 19, 20])

In [8]:
arr[3:]

array([14, 15, 16, 17, 18, 19, 20])

In [13]:
arr_slice = arr[3::2] #3rd colon is for gap
arr_slice #Slicing returns the sliced array

array([14, 16, 18, 20])

Numpy indexing and slicing of matrix

In [16]:
arr = np.arange(1, 31).reshape(6, 5)
arr

array([[ 1,  2,  3,  4,  5],
       [ 6,  7,  8,  9, 10],
       [11, 12, 13, 14, 15],
       [16, 17, 18, 19, 20],
       [21, 22, 23, 24, 25],
       [26, 27, 28, 29, 30]])

In [17]:
arr[0]

array([1, 2, 3, 4, 5])

In [21]:
arr[0][0] #Indexing

np.int64(1)

In [20]:
arr[0,0] #Indexing

np.int64(1)

In [26]:
slic = arr[:2, 1:3] #Combined row-col slicing
slic

array([[2, 3],
       [7, 8]])

In [28]:
slic = arr[3:, 3:]
slic

array([[19, 20],
       [24, 25],
       [29, 30]])

Boolean Indexing

In [33]:
arr = np.arange(11, 21)
arr

array([11, 12, 13, 14, 15, 16, 17, 18, 19, 20])

In [34]:
bool_idx = arr % 2 == 0
bool_idx

array([False,  True, False,  True, False,  True, False,  True, False,
        True])

In [35]:
arr = arr[bool_idx]
arr

array([12, 14, 16, 18, 20])