In [4]:
import numpy as np

Numpy Exercises

1. Valid Sudoku

For a sudoku to be valid the conditions are:

a. each row and column sum should be equal to 45

b. every consicutive 3x3 block should have the sum equal to 45

In [46]:
s = np.array([
    [5, 3, 4, 6, 7, 8, 9, 1, 2],
    [6, 7, 2, 1, 9, 5, 3, 4, 8],
    [1, 9, 8, 3, 4, 2, 5, 6, 7],
    
    [8, 5, 9, 7, 6, 1, 4, 2, 3],
    [4, 2, 6, 8, 5, 3, 7, 9, 1],
    [7, 1, 3, 9, 2, 4, 8, 5, 6],
    
    [9, 6, 1, 5, 3, 7, 2, 8, 4],
    [2, 8, 7, 4, 1, 9, 6, 3, 5],
    [3, 4, 5, 2, 8, 6, 1, 7, 9]
])

In [47]:
rs = np.sum(s, axis=1)
for i in rs:
    if i != 45:
        print("Invalid Sudoku")
        break
else:
    print("For rows its valid")

For rows its valid


In [48]:
cs = np.sum(s, axis=0)
for i in rs:
    if i != 45:
        print("Invalid Sudoku")
        break
else:
    print("For columns its valid")

For columns its valid


In [49]:
for i in range(0, 9, 3):
    isValid = True
    for j in range(0, 9, 3):
        sum = np.sum(s[i:i+3, j:j+3])
        if sum != 45:
            isValid = False
            break
    if(not isValid):
        print("Invalid Sudoku")
        break
else:
    print("Valid Sudoku")

Valid Sudoku


2. General Questions

In [175]:
# Columns: [Age, Math Marks, Science Marks]
data = np.array([
    [18, 85, 78],   # Student 1
    [19, 92, 88],   # Student 2
    [17, 76, 95],   # Student 3
    [18, 65, 70],   # Student 4
    [20, 90, 85]    # Student 5
])

a. Get the shape of the matrix.

In [176]:
data.shape

(5, 3)

b. Find the average age of students.

In [177]:
s = np.sum(data, axis=0)
avg = s / 5
avg[0]

np.float64(18.4)

c. Extract Math marks of all students.

In [178]:
math = data[:, 1:2]
math

array([[85],
       [92],
       [76],
       [65],
       [90]])

d. Find the highest Science mark.

In [179]:
science = data[:, 2:3]
np.max(science)

np.int64(95)

e. Get details of the student who scored more than 90 in Math.

In [180]:
data[data[:, 1] > 90]

array([[19, 92, 88]])

f. Increase Math marks of all students by 5.

In [181]:
data[:, 1] += 5
data

array([[18, 90, 78],
       [19, 97, 88],
       [17, 81, 95],
       [18, 70, 70],
       [20, 95, 85]])

g. Find how many students are younger than 19.

In [182]:
len(data[data[:, 0] < 19])

3

h. Calculate the average marks in each subject (column-wise mean).

In [183]:
np.mean(data[:, 1:], axis=0)

array([86.6, 83.2])

i. Get data of students who scored at least 80 in both subjects.

In [184]:
data[(data[:, 1] >= 80) & (data[:, 2] >= 80)]

array([[19, 97, 88],
       [17, 81, 95],
       [20, 95, 85]])

j. Replace all Science marks < 75 with 0.

In [185]:
data[:, 2][data[:, 2] < 75] = 0
data

array([[18, 90, 78],
       [19, 97, 88],
       [17, 81, 95],
       [18, 70,  0],
       [20, 95, 85]])