In [1]:
import numpy as np

In [111]:
# Columns:
# [student_id, age, study_hours, height_cm, weight_kg, passed]
data = np.array([
    [101, 20, 72, 180, 65, 1],
    [102, 21, 68, 165, 58, 0],
    [103, 19, 75, 175, 72, 1],
    [104, 22, 80, 182, 80, 1],
    [105, 20, 65, 160, 52, 0],
    [106, 23, 90, 185, 88, 1],
    [107, 21, 70, 170, 61, 0],
    [108, 24, 85, 178, 76, 1],
    [109, 19, 62, 158, 50, 0],
    [110, 22, 77, 172, 69, 1],
    [111, 20, 73, 168, 63, 1],
    [112, 23, 66, 164, 57, 0]
])

1. Find the shape, number of dimensions, total number of elements, and data type of data.

In [112]:
data.shape

(12, 6)

In [113]:
data.ndim

2

In [114]:
data.dtype

dtype('int64')

In [115]:
data.size

72

2. Extract the complete first row.

In [116]:
data[0, :]

array([101,  20,  72, 180,  65,   1])

3. Extract the student ID of the student in the 8th row.

In [117]:
data[7,0]

np.int64(108)

4. Extract the complete study_hours column.

In [118]:
data[:, 2]

array([72, 68, 75, 80, 65, 90, 70, 85, 62, 77, 73, 66])

5. Extract the last 5 rows of the dataset.

In [119]:
data[7:, :]

array([[108,  24,  85, 178,  76,   1],
       [109,  19,  62, 158,  50,   0],
       [110,  22,  77, 172,  69,   1],
       [111,  20,  73, 168,  63,   1],
       [112,  23,  66, 164,  57,   0]])

6. Extract the first 4 rows and only the age, study_hours, and height_cm columns.

In [120]:
data[:4, 1:4]

array([[ 20,  72, 180],
       [ 21,  68, 165],
       [ 19,  75, 175],
       [ 22,  80, 182]])

7. Calculate the average age, study hours, height, and weight of all students.

In [121]:
np.mean(data[:, 1:5], axis=0)

array([ 21.16666667,  73.58333333, 171.41666667,  65.91666667])

8. Find the minimum and maximum study hours. Also find the student IDs of the students with the minimum and maximum study hours.

In [122]:
np.min(data[:, 2], axis=0)

np.int64(62)

In [123]:
np.max(data[:, 2], axis=0)

np.int64(90)

In [124]:
np.argmin(data[:, 2], axis=0)

np.int64(8)

In [125]:
np.argmax(data[:, 2], axis=0)

np.int64(5)

9. Calculate the sum of every column using axis=0.

In [126]:
np.sum(data, axis=0)

array([1278,  254,  883, 2057,  791,    7])

10. Calculate the average of every column using axis=0.

In [127]:
np.mean(data, axis=0)

array([106.5       ,  21.16666667,  73.58333333, 171.41666667,
        65.91666667,   0.58333333])

11. Calculate the average study hours of students who passed.

In [128]:
np.average(data[:,2][data[:, 5] == 1], axis=0)

np.float64(78.85714285714286)

12. Calculate the average weight of students who failed.

In [129]:
np.average(data[:,4][data[:,5] == 0], axis=0)

np.float64(55.6)

13. Extract all students who studied more than 75 hours.

In [130]:
data[data[:,2] > 75]

array([[104,  22,  80, 182,  80,   1],
       [106,  23,  90, 185,  88,   1],
       [108,  24,  85, 178,  76,   1],
       [110,  22,  77, 172,  69,   1]])

14. Extract all students whose study hours are between 65 and 80, inclusive.

In [131]:
data[(data[:,2] >= 65) & (data[:,2] <= 80)]

array([[101,  20,  72, 180,  65,   1],
       [102,  21,  68, 165,  58,   0],
       [103,  19,  75, 175,  72,   1],
       [104,  22,  80, 182,  80,   1],
       [105,  20,  65, 160,  52,   0],
       [107,  21,  70, 170,  61,   0],
       [110,  22,  77, 172,  69,   1],
       [111,  20,  73, 168,  63,   1],
       [112,  23,  66, 164,  57,   0]])

15. Extract all students who are at least 21 years old and studied more than 70 hours.

In [132]:
data[(data[:, 1] >= 21) & (data[:,2] > 70)]

array([[104,  22,  80, 182,  80,   1],
       [106,  23,  90, 185,  88,   1],
       [108,  24,  85, 178,  76,   1],
       [110,  22,  77, 172,  69,   1]])

16. Extract all students who either studied less than 65 hours or weigh more than 75 kg.

In [133]:
data[(data[:,2] < 65) | (data[:,4] > 75)]

array([[104,  22,  80, 182,  80,   1],
       [106,  23,  90, 185,  88,   1],
       [108,  24,  85, 178,  76,   1],
       [109,  19,  62, 158,  50,   0]])

17. Count how many students passed and how many failed. Do this without using a Python loop.

In [134]:
len(data[data[:,5] == 1])

7

In [135]:
len(data[data[:,5] == 0])

5

18. Create a new array containing only the study_hours, height_cm, and weight_kg columns.

In [136]:
nArr = data[:, 2:5]
nArr

array([[ 72, 180,  65],
       [ 68, 165,  58],
       [ 75, 175,  72],
       [ 80, 182,  80],
       [ 65, 160,  52],
       [ 90, 185,  88],
       [ 70, 170,  61],
       [ 85, 178,  76],
       [ 62, 158,  50],
       [ 77, 172,  69],
       [ 73, 168,  63],
       [ 66, 164,  57]])

19. Calculate the mean of each of those three columns.

In [137]:
np.sum(nArr, axis=0)

array([ 883, 2057,  791])

20. Subtract the corresponding column mean from every student's values using broadcasting.

In [138]:
nArr - np.mean(nArr, axis=0)

array([[ -1.58333333,   8.58333333,  -0.91666667],
       [ -5.58333333,  -6.41666667,  -7.91666667],
       [  1.41666667,   3.58333333,   6.08333333],
       [  6.41666667,  10.58333333,  14.08333333],
       [ -8.58333333, -11.41666667, -13.91666667],
       [ 16.41666667,  13.58333333,  22.08333333],
       [ -3.58333333,  -1.41666667,  -4.91666667],
       [ 11.41666667,   6.58333333,  10.08333333],
       [-11.58333333, -13.41666667, -15.91666667],
       [  3.41666667,   0.58333333,   3.08333333],
       [ -0.58333333,  -3.41666667,  -2.91666667],
       [ -7.58333333,  -7.41666667,  -8.91666667]])

21. Create the array [2, 5, 3]. Add it to every student's study_hours, height_cm, and weight_kg values using broadcasting.

In [139]:
bd = np.array([2, 5, 3])
nArr + bd

array([[ 74, 185,  68],
       [ 70, 170,  61],
       [ 77, 180,  75],
       [ 82, 187,  83],
       [ 67, 165,  55],
       [ 92, 190,  91],
       [ 72, 175,  64],
       [ 87, 183,  79],
       [ 64, 163,  53],
       [ 79, 177,  72],
       [ 75, 173,  66],
       [ 68, 169,  60]])

22. Create the weight vector [0.5, 0.2, 0.3] and calculate a score for every student using matrix multiplication (@).

In [140]:
mul = np.array([0.5, 0.2, 0.3])
score = nArr @ mul
score

array([ 91.5,  84.4,  94.1, 100.4,  80.1, 108.4,  87.3, 100.9,  77.6,
        93.6,  89. ,  82.9])

23. Find the index of the student with the highest score.

In [141]:
np.argmax(score)

np.int64(5)

24. Using that index, extract the student's ID, score, and complete row from the original dataset.

In [142]:
data[np.argmax(score), :]

array([106,  23,  90, 185,  88,   1])

25. Create two 1D arrays and combine them using np.concatenate(), np.vstack(), and np.hstack(). Observe the resulting arrays and their shapes.

In [143]:
a = np.array([1, 2, 3, 4])
b = np.array([5, 6, 7, 8])

In [144]:
np.concatenate((a, b))

array([1, 2, 3, 4, 5, 6, 7, 8])

In [145]:
np.vstack((a, b))

array([[1, 2, 3, 4],
       [5, 6, 7, 8]])

In [146]:
np.hstack((a, b))

array([1, 2, 3, 4, 5, 6, 7, 8])

26. Create two 2D arrays and [[1, 2], [3, 4]] and [[5, 6], [7, 8]] ans use np.concatenate() with axis=0 and axis=1. Then compare the results with np.vstack() and np.hstack().

In [147]:
a = np.array([[1, 2], [3, 4]])
b = np.array([[5, 6], [7, 8]])

In [148]:
np.concatenate((a, b))

array([[1, 2],
       [3, 4],
       [5, 6],
       [7, 8]])

In [149]:
np.concatenate((a, b), axis=0)

array([[1, 2],
       [3, 4],
       [5, 6],
       [7, 8]])

In [150]:
np.concatenate((a, b), axis=1)

array([[1, 2, 5, 6],
       [3, 4, 7, 8]])

In [151]:
np.vstack((a, b))

array([[1, 2],
       [3, 4],
       [5, 6],
       [7, 8]])

In [152]:
np.hstack((a, b))

array([[1, 2, 5, 6],
       [3, 4, 7, 8]])

27. Create an array [10, 20, 30, 40, 50]. Make a copy of it, change the first element of the copy to 1, and check whether the original changed.

In [153]:
a = np.array([10, 20, 30, 40, 50])
b = a

In [154]:
b[0] = 1

In [155]:
a

array([ 1, 20, 30, 40, 50])

In [156]:
b

array([ 1, 20, 30, 40, 50])

This happened because directly copying creates a shallow copy which means b is pointing to the same memory location to which a is pointing.

In [157]:
a = np.array([10, 20, 30, 40, 50])
b = a.copy()

In [158]:
b[0] = 1

In [159]:
a

array([10, 20, 30, 40, 50])

In [160]:
b

array([ 1, 20, 30, 40, 50])

This is called a deep copy another array is created in memory to which b is pointing not the same as a.

28. Create an array [10, 20, 30, 40, 50]. Create a slice containing elements 2–4, modify the first element of the slice, and check whether the original array changed. Determine whether the slice is behaving as a view or an independent copy.

In [161]:
a

array([10, 20, 30, 40, 50])

In [162]:
b = a[1:4]
b

array([20, 30, 40])

In [163]:
b[0] = 200

In [164]:
b

array([200,  30,  40])

In [165]:
a

array([ 10, 200,  30,  40,  50])

Slicing behaves like a view cause changing the view changes the original too.

In [166]:
a[1] = 20

In [167]:
a

array([10, 20, 30, 40, 50])

In [168]:
b = a[1:4].copy()

In [169]:
b[0] = 200
b

array([200,  30,  40])

In [170]:
a

array([10, 20, 30, 40, 50])

Deep copy using copy method during slicing. 

29. Find the student IDs of all students who passed and studied more than the overall average study hours, and weigh less than the overall average weight.

In [171]:
data

array([[101,  20,  72, 180,  65,   1],
       [102,  21,  68, 165,  58,   0],
       [103,  19,  75, 175,  72,   1],
       [104,  22,  80, 182,  80,   1],
       [105,  20,  65, 160,  52,   0],
       [106,  23,  90, 185,  88,   1],
       [107,  21,  70, 170,  61,   0],
       [108,  24,  85, 178,  76,   1],
       [109,  19,  62, 158,  50,   0],
       [110,  22,  77, 172,  69,   1],
       [111,  20,  73, 168,  63,   1],
       [112,  23,  66, 164,  57,   0]])

In [172]:
data[:, 0][(data[:, 5] == 1) & (data[:,2] > np.mean(data[:, 2], axis=0)) & (data[:, 4] < np.mean(data[:, 4], axis=0))]

array([], dtype=int64)

30. Find the student who has the highest study hours among students who passed. Return their student ID, study hours, and complete row.

In [173]:
data[(data[:,2] == np.max(data[:,2], axis=0)) & (data[:,5] == 1)]

array([[106,  23,  90, 185,  88,   1]])

31. Normalize the study_hours column using normalized = (x - mean) / standard_deviation, then verify that the resulting column has a mean approximately equal to 0 and a standard deviation approximately equal to 1.

In [174]:
data[:,2] = (data[:,2] - np.mean(data[:,2], axis=0)) / np.std(data[:, 2], axis=0)

In [175]:
data

array([[101,  20,   0, 180,  65,   1],
       [102,  21,   0, 165,  58,   0],
       [103,  19,   0, 175,  72,   1],
       [104,  22,   0, 182,  80,   1],
       [105,  20,  -1, 160,  52,   0],
       [106,  23,   2, 185,  88,   1],
       [107,  21,   0, 170,  61,   0],
       [108,  24,   1, 178,  76,   1],
       [109,  19,  -1, 158,  50,   0],
       [110,  22,   0, 172,  69,   1],
       [111,  20,   0, 168,  63,   1],
       [112,  23,   0, 164,  57,   0]])

In [176]:
np.mean(data[:,2], axis=0)

np.float64(0.08333333333333333)

In [177]:
np.std(data[:,2], axis=0)

np.float64(0.759202798262025)