In [12]:
import numpy as np

Vector creation

In [48]:
arr = np.array([1,2,3,4,5,6])
arr

array([1, 2, 3, 4, 5, 6])

Matrix Creation but not visual in list

In [19]:
ls = [[1, 2, 3], [4, 5, 6], [7, 8, 9]]
ls

[[1, 2, 3], [4, 5, 6], [7, 8, 9]]

Matrix Visual in numpy arrays

In [27]:
arr = np.array(ls)
arr

array([[1, 2, 3],
       [4, 5, 6],
       [7, 8, 9]])

In [23]:
arr = np.arange(1, 10, 1)
arr

array([1, 2, 3, 4, 5, 6, 7, 8, 9])

Fixed value auto generated array

In [24]:
arr = np.zeros(6)
arr

array([0., 0., 0., 0., 0., 0.])

In [29]:
arr = np.zeros((4, 8))
arr

array([[0., 0., 0., 0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0., 0., 0., 0.]])

In [31]:
arr = np.ones((4, 2))
arr

array([[1., 1.],
       [1., 1.],
       [1., 1.],
       [1., 1.]])

Linear space array different from arange

In [37]:
arr = np.linspace(0, 1, 10)
arr

array([0.        , 0.11111111, 0.22222222, 0.33333333, 0.44444444,
       0.55555556, 0.66666667, 0.77777778, 0.88888889, 1.        ])

Random Number Array

In [40]:
arr = np.random.rand(5)
arr

array([0.18994925, 0.22643222, 0.95933826, 0.48124866, 0.84461677])

In [42]:
arr = np.random.randn(5)
arr

array([ 0.60583893,  0.84663144, -0.46103846, -0.4902548 , -0.70431357])

In [44]:
arr = np.random.randint(10, 20, 10)
arr

array([15, 10, 19, 11, 17, 12, 14, 17, 11, 15])

Array Attributes

In [49]:
arr = np.array([[1, 2, 3], [4, 5, 6], [7, 8, 9]])
arr

array([[1, 2, 3],
       [4, 5, 6],
       [7, 8, 9]])

In [50]:
arr.shape

(3, 3)

In [51]:
arr.size

9

In [52]:
arr.dtype

dtype('int64')

Array Methods

In [53]:
arr = np.array([[1, 2, 3], [4, 5, 6], [7, 8, 9]])
arr

array([[1, 2, 3],
       [4, 5, 6],
       [7, 8, 9]])

In [54]:
arr.min()

np.int64(1)

In [55]:
arr.max()

np.int64(9)

In [56]:
arr.sum()

np.int64(45)

In [59]:
np.sum(arr, axis=0) #Column Axis

array([12, 15, 18])

In [60]:
np.sum(arr, axis=1) #Row Axis

array([ 6, 15, 24])

In [64]:
arr.mean() #Mean of the data

np.float64(5.0)

In [65]:
arr.std() #Standard Deviation of the data

np.float64(2.581988897471611)

In [68]:
arr.argmax() #Index of max element

np.int64(8)

In [69]:
arr.argmin() #Index of min element

np.int64(0)

Reshaping and resizing

In [71]:
arr = np.arange(1, 31)
arr

array([ 1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14, 15, 16, 17,
       18, 19, 20, 21, 22, 23, 24, 25, 26, 27, 28, 29, 30])

In [73]:
arr = arr.reshape(6, 5) #The element count should be the same
arr
#Reshaping is just changing the shape
#Resising is changing the shape and putting it back into orignal arr

array([[ 1,  2,  3,  4,  5],
       [ 6,  7,  8,  9, 10],
       [11, 12, 13, 14, 15],
       [16, 17, 18, 19, 20],
       [21, 22, 23, 24, 25],
       [26, 27, 28, 29, 30]])